name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: gcc-update
      run: sudo apt-get update && sudo apt-get install gcc-9
    - name: cmake
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DUSE_CLANG=0 -DBUILD_TESTS=1 ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
